conf/layer.conf: Support Blacksail
Set the layer compatibility to the Yocto Project release Blacksail
following the recent change in openembedded-core:
https://git.openembedded.org/openembedded-core/commit/?id=37623ffbdd34a5c6b3e12ee33195f8e82343f198

Fixes:

ERROR: Layer clang-layer is not compatible with the core layer
which only supports these series: blacksail (layer is compatible
with wrynose)

This work was sponsored by GOVCERT.LU.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>